version: "3"
services:
    nginx:
        image: mynode-nginx
        #volumes:
        #    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - node-app
    node-app:
        build: .
        environment: 
            - PORT=3000
        deploy:
            replicas: 2
        #start mongo container first, but doesnt check processes are up
        depends_on:
            - mongo

    mongo:
        image: mongo
        volumes: 
            - mongo-db:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

    redis:
        image: redis
        

volumes: 
    mongo-db: 